
# [START runtime]
runtime: nodejs10
handlers:
  - url: / 
    static_files: smart_contracts/public/index.html
    upload: smart_contracts/public/index.html
  - url: /
    static_dir: smart_contracts/public
# [END runtime]